baseURL = "http://exx1135-enprod.exxoss.net/"
languageCode = "fr-be"
title = "Résiste !"
disableKinds = ["taxonomy", "taxonomyTerm", "sitemap", "RSS"]

[params]
    description = "Le jeu coopératif pour résister ensemble et défendre la démocratie !"
