name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
          
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          
      - name: Install npm dependencies
        run: npm i

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.62.2'
          extended: true

      - name: Build
        run: hugo --minify
        
      - name: SSH setup
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "${KNOWN_HOSTS}" >> ~/.ssh/known_hosts
          echo "${DEPLOY_KEY}" > ~/.ssh/my_rsync_key
          echo "IdentityFile ~/.ssh/my_rsync_key" >> ~/.ssh/config
          chmod -R 700 ~/.ssh

      - name: Rsync deployment
        run: |
          rsync -avz -e ssh --delete public/ ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_DESTINATION }}

        
      # - name: rsync deployments
      #   uses: contention/rsync-deployments@v1.0.0
      #   env: 
      #     DEPLOY_KEY: ${{secrets.DEPLOY_KEY}} 
      #   with: 
      #     args: "-avz --delete-after public/ ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_DESTINATION }}"
