name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1  # v2 does not have submodules option now
        # with:
        #   submodules: true
          
      - name: Install npm dependencies
        run: npm i

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.62.2'
          extended: true

      - name: Build
        run: hugo --minify
        
      - name: rsync deployments
        uses: contention/rsync-deployments@v1.0.0
        env: 
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}} 
        with: 
          args: "-r --delete-after public/* ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_DESTINATION }}"
